// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'degfault': string;
  'rete-background': string;
}
export const cssExports: CssExports;
export default cssExports;
