// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'folder-arrow': string;
  'list-item': string;
  'menu-bar': string;
  'menu-bar-item': string;
  'menu-panel': string;
  'thoth-logo': string;
}
export const cssExports: CssExports;
export default cssExports;
