export const modelMap = {
  gptj: {
    name: 'GPT-J',
    model: 'gpt-j-6b-story-gutenberg-rw-bibliotik-raw',
    modelSource: 'coreweave',
    text: 'A long time ago, in a galaxy far far away there was',
    length: 45,
    topP: 0.9,
    n: 4,
    temperature: 1,
    universalFormat: true,
  },
  jurassicJumbo: {
    name: 'Jurassic Jumbo',
    model: 'j1-jumbo',
    modelSource: 'ai21',
    prompt: 'A long time ago, in a galaxy far far away there was',
    maxTokens: 45,
    n: 3,
    temperature: 1,
    stop: '\n',
    universalFormat: true,
  },
  jurassicLarge: {
    name: 'Jurassic Large',
    model: 'j1-large',
    modelSource: 'ai21',
    prompt: 'A long time ago, in a galaxy far far away there was',
    maxTokens: 45,
    n: 3,
    temperature: 1,
    stop: '\n',
    universalFormat: true,
  },
  openai: {
    modelSource: 'openai',
    model: 'davinci',
    prompt: 'Once upon a time in a forgotten forest',
    temperature: 0.7,
    maxTokens: 120,
    stop: '\n',
    n: 3,
    universalFormat: true,
  },
  forefront: {
    name: 'forefront',
    modelSource: 'forefront',
    model: 'forefront model',
    prompt: 'A long time ago, in a galaxy far far away there was',
    maxTokens: 50,
    topP: 0.9,
    n: 2,
    universalFormat: true,
    temperature: 1,
  },
}
