// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'editor-container': string;
  'editor-toolbar': string;
  'folder-arrow': string;
  'list-item': string;
}
export const cssExports: CssExports;
export default cssExports;
